// This file is auto-generated by scripts/generate-vite-configs.mjs
// Edit scripts/vite-config-manifest.mjs and regenerate instead of editing manually.
import { createDockletCoreAlias, createObsidianViteConfig } from '../scripts/obsidianViteConfig';

export default createObsidianViteConfig({
	entry: 'src/main.ts',
	name: 'DockletWordViewer',
	alias: {
		...createDockletCoreAlias(),
	},
});
